"""empty message

Revision ID: 9f84ae3c1156
Revises: cfdb3dfbca24
Create Date: 2024-07-03 13:42:46.156038

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f84ae3c1156'
down_revision: Union[str, None] = 'cfdb3dfbca24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('bio', sa.String(), nullable=True),
                    sa.Column('image', sa.String(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__Users'))
                    )
    op.create_index(op.f('ix__Users__id'), 'Users', ['id'], unique=False)
    op.create_table('Articles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
                    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name=op.f('fk__Articles__author_id__Users'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__Articles'))
                    )
    op.create_index(op.f('ix__Articles__id'), 'Articles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__Articles__id'), table_name='Articles')
    op.drop_table('Articles')
    op.drop_index(op.f('ix__Users__id'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
