"""empty message

Revision ID: a64b5f60d0ff
Revises: 
Create Date: 2024-07-06 19:18:38.422555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64b5f60d0ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Users'))
    )
    op.create_index(op.f('ix__Users__id'), 'Users', ['id'], unique=False)
    op.create_table('Articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name=op.f('fk__Articles__author_id__Users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Articles'))
    )
    op.create_index(op.f('ix__Articles__id'), 'Articles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__Articles__id'), table_name='Articles')
    op.drop_table('Articles')
    op.drop_index(op.f('ix__Users__id'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
