"""empty message

Revision ID: aeb68986e95b
Revises: 88267e58f3b6
Create Date: 2024-07-04 19:25:44.917207

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeb68986e95b'
down_revision: Union[str, None] = '88267e58f3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Articles', 'updated_at')
    op.drop_column('Articles', 'created_at')
    op.drop_column('Users', 'updated_at')
    op.drop_column('Users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"),
                                     autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"),
                                     autoincrement=False, nullable=False))
    op.add_column('Articles',
                  sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"),
                            autoincrement=False, nullable=False))
    op.add_column('Articles',
                  sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"),
                            autoincrement=False, nullable=False))
    # ### end Alembic commands ###
