"""empty message

Revision ID: c7ea5ba1e334
Revises: 9f84ae3c1156
Create Date: 2024-07-04 18:38:06.039897

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7ea5ba1e334'
down_revision: Union[str, None] = '9f84ae3c1156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Articles', sa.Column('name', sa.String(), nullable=False))
    op.add_column('Users',
                  sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('Users',
                  sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'updated_at')
    op.drop_column('Users', 'created_at')
    op.drop_column('Articles', 'name')
    # ### end Alembic commands ###
