"""empty message

Revision ID: f1762d4aeab8
Revises: a64b5f60d0ff
Create Date: 2024-07-06 19:23:39.540021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1762d4aeab8'
down_revision: Union[str, None] = 'a64b5f60d0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Articles', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq__Articles__slug'), 'Articles', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__Articles__slug'), 'Articles', type_='unique')
    op.drop_column('Articles', 'slug')
    # ### end Alembic commands ###
