"""empty message

Revision ID: fbc959194baf
Revises: 307b5fb5b2f9
Create Date: 2024-07-09 14:32:25.275072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc959194baf'
down_revision: Union[str, None] = '307b5fb5b2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
