"""empty message

Revision ID: 3e5a00efdcc8
Revises: 82f6697070ce
Create Date: 2024-06-29 13:37:42.663970

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e5a00efdcc8'
down_revision: Union[str, None] = '82f6697070ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(), nullable=False))
    op.add_column('User', sa.Column('email', sa.Integer(), nullable=False))
    op.add_column('User', sa.Column('bio', sa.String(), nullable=False))
    op.add_column('User', sa.Column('image', sa.String(), nullable=False))
    op.drop_column('User', 'age')
    op.drop_column('User', 'name')
    op.drop_column('User', 'passport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('passport', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('User', 'image')
    op.drop_column('User', 'bio')
    op.drop_column('User', 'email')
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
