"""empty message

Revision ID: 82f6697070ce
Revises: 0baa6416d268
Create Date: 2024-06-27 23:40:46.026802

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '82f6697070ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Test_id', table_name='Test')
    op.drop_table('Test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='Test_pkey')
                    )
    op.create_index('ix_Test_id', 'Test', ['id'], unique=False)
    # ### end Alembic commands ###
