"""empty message

Revision ID: b4b1db14b59e
Revises: 3e5a00efdcc8
Create Date: 2024-06-29 16:19:02.587213

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4b1db14b59e'
down_revision: Union[str, None] = '3e5a00efdcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('email', sa.Integer(), nullable=False),
                    sa.Column('bio', sa.String(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.drop_index('ix_User_id', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('email', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='User_pkey')
                    )
    op.create_index('ix_User_id', 'User', ['id'], unique=False)
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
