"""empty message

Revision ID: c1c735a2e1c6
Revises: 561974e39740
Create Date: 2024-06-29 17:01:54.659984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c735a2e1c6'
down_revision: Union[str, None] = '561974e39740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'email',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_Users_id', table_name='Users')
    op.create_index(op.f('ix__Users__id'), 'Users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__Users__id'), table_name='Users')
    op.create_index('ix_Users_id', 'Users', ['id'], unique=False)
    op.alter_column('Users', 'email',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
